[meta]
name     = "Pre-Cache Maps"
author   = "XertroV"
category = "Utilities"
version  = "0.9.0"

[script]
#__DEFINES__
# dependencies = ["MLFeedRaceData"]
dependencies = ["MLHook"]
optional_dependencies = ["BetterRoomManager"]
exports = ["PreCacher_Export.as"]
module = "PreCacher"
